import 'wml!Controls-demo/DevicesInfo/columnTemplates/DevicesInfoDeviceList';
import 'wml!Controls-demo/DevicesInfo/columnTemplates/DevicesInfoDateList';
import 'wml!Controls-demo/DevicesInfo/columnTemplates/DevicesInfoLocationList';
import 'wml!Controls-demo/DevicesInfo/columnTemplates/DevicesInfoIconsList';
import {showType} from 'Controls/Utils/Toolbar';
import {IItemAction} from 'Controls/_list/interface/IList';

function getColumns() {
    return [
        {
            template: 'wml!Controls-demo/DevicesInfo/columnTemplates/DevicesInfoDeviceList',
            width: '3fr'
        }, {
            template: 'wml!Controls-demo/DevicesInfo/columnTemplates/DevicesInfoDateList',
            width: '75px'
        }, {
            template: 'wml!Controls-demo/DevicesInfo/columnTemplates/DevicesInfoLocationList',
            width: '1fr'
        }, {
            template: 'wml!Controls-demo/DevicesInfo/columnTemplates/DevicesInfoIconsList',
            width: '90px'
        }
    ];
}
function getDevicesTrusted() {
    return {
        getData: () => [
            {
                "@УстройстваПользователя": 9651944,
                Доверенное: false,
                Мое: true,
                NewDevice: "0d12c7d2-2fa0-2c2a-3cae-7b62ace9dd63",
                Название: "TSD-KRAS",
                Пользователь: 861523,
                IP: "10.76.190.133",
                ПоследнийВход: "2020-04-14 14:24:10.816342+03",
                ОС: "Windows 7",
                Браузер: "Chrome 80.0.3987",
                Город: "Ярославль",
                ВСети: false,
                Work: true,
                New: false,
                Blocked: null,
                type: 1,
                real_name: "TSD-KRAS",
                archive: false,
                EnterType:'00ba',
                Status: 2,
                model: null,
                is_plugin: true,
                id: 0,
                testType: 2
            },
            {
                "@УстройстваПользователя": 9912662,
                Доверенное: false,
                Мое: false,
                NewDevice: "93a6a62a-313e-65a3-675c-5478c1f02c16",
                Название: "R78-ZAHMATOV",
                Пользователь: 861523,
                IP: "10.176.134.156",
                ПоследнийВход: "2020-04-14 14:25:18.856370+03",
                ОС: "Windows 10",
                Браузер: "Chrome 80.0.3987",
                Город: "Рыбинск",
                ВСети: false,
                Work: null,
                New: false,
                Blocked: null,
                type: 0,
                real_name: "R78-ZAHMATOV",
                archive: false,
                EnterType: "00ba",
                Status: 2,
                model: null,
                is_plugin: true,
                id: 1,
                testType: 2
            },
            {
                "@УстройстваПользователя": 9692623,
                Доверенное: false,
                Мое: false,
                NewDevice: "a6047745-879e-c413-7f36-0f1f41661a85",
                Название: "R44-COMP90",
                Пользователь: 861523,
                IP: "10.44.15.37",
                ПоследнийВход: "2020-04-14 14:24:56.522297+03",
                ОС: "Windows 7",
                Браузер: "Chrome 80.0.3987",
                Город: "Кострома",
                ВСети: false,
                Work: false,
                New: false,
                Blocked: null,
                type: 0,
                real_name: "R44-COMP90",
                archive: false,
                EnterType: "00ba",
                Status: 2,
                model: null,
                is_plugin: true,
                id: 2,
                testType: 2
            },
            {
                "@УстройстваПользователя": 9711945,
                Доверенное: false,
                Мое: false,
                NewDevice: "ee0001e8-2ea4-79ec-2a8c-f846636eb219",
                Название: "R78-DOLMATOV2",
                Пользователь: 861523,
                IP: "10.78.14.56",
                ПоследнийВход: "2020-04-14 14:24:52.911089+03",
                ОС: "Windows 10",
                Браузер: "Chrome 80.0.3987",
                Город: "Санкт-Петербург",
                ВСети: false,
                Work: null,
                New: false,
                Blocked: null,
                type: 0,
                real_name: "R78-DOLMATOV2",
                archive: false,
                EnterType: "00ba",
                Status: 2,
                model: null,
                is_plugin: true,
                id: 3,
                testType: 2
            },
            {
                "@УстройстваПользователя": 9716185,
                Доверенное: false,
                Мое: false,
                NewDevice: "800e73b9-b271-2235-348d-cbacb79801aa",
                Название: "R72-PROG40",
                Пользователь: 861523,
                IP: "10.176.131.64",
                ПоследнийВход: "2020-04-14 14:24:47.361597+03",
                ОС: "Windows 7",
                Браузер: "Chrome 80.0.3987",
                Город: "Рыбинск",
                ВСети: false,
                Work: null,
                New: false,
                Blocked: null,
                type: 0,
                real_name: "R72-PROG40",
                archive: false,
                EnterType: "00ba",
                Status: 2,
                model: null,
                is_plugin: true,
                id: 4,
                testType: 1
            },
            {
                "@УстройстваПользователя": 9741827,
                Доверенное: false,
                Мое: false,
                NewDevice: null,
                Название: "Устройство не определено",
                Пользователь: 861523,
                IP: "10.76.146.187",
                ПоследнийВход: "2020-04-14 14:24:41.753436+03",
                ОС: "Other",
                Браузер: "ZabbixCaller",
                Город: "Ярославль",
                ВСети: false,
                Work: false,
                New: false,
                Blocked: false,
                type: 3,
                real_name: "Устройство не определено",
                archive: false,
                EnterType: "00ba",
                Status: 2,
                model: null,
                is_plugin: false,
                id: 5,
                testType: 0
            }, {
                "@УстройстваПользователя": 10005208,
                Доверенное: false,
                Мое: false,
                NewDevice: null,
                Название: "Windows 7",
                Пользователь: 861523,
                IP: "10.176.134.144",
                ПоследнийВход: "2020-04-14 14:24:11.476807+03",
                ОС: "Windows 7",
                Браузер: "Chrome 80.0.3987",
                Город: "Рыбинск",
                ВСети: false,
                Work: null,
                New: false,
                Blocked: null,
                type: 0,
                real_name: "Windows 7",
                archive: false,
                EnterType: "00ba",
                Status: 2,
                model: null,
                is_plugin: false,
                id: 6,
                testType: 1
            }, {
                "@УстройстваПользователя": 9542638,
                Доверенное: false,
                Мое: false,
                NewDevice: "cff59b34-ac20-d344-ecf6-32bfd645c7d8",
                Название: "R78-PROHOROVA",
                Пользователь: 861523,
                IP: "10.78.14.22",
                ПоследнийВход: "2020-04-14 14:20:03.584340+03",
                ОС: "Windows 7",
                Браузер: "Chrome 80.0.3987",
                Город: "Санкт-Петербург",
                ВСети: false,
                Work: null,
                New: false,
                Blocked: false,
                type: 0,
                real_name: "R78-PROHOROVA",
                archive: false,
                EnterType: "00ba",
                Status: 1,
                model: null,
                is_plugin: true,
                id: 7,
                testType: 0
            }, {
                "@УстройстваПользователя": 10008659,
                Доверенное: false,
                Мое: false,
                NewDevice: null,
                Название: "Windows 10",
                Пользователь: 861523,
                IP: "10.176.132.163",
                ПоследнийВход: "2020-04-14 14:19:24.757207+03",
                ОС: "Windows 10",
                Браузер: "Chrome 80.0.3987",
                Город: "Рыбинск",
                ВСети: false,
                Work: null,
                New: true,
                Blocked: null,
                type: 0,
                real_name: "Windows 10",
                archive: false,
                EnterType: "00ba",
                Status: 1,
                model: null,
                is_plugin: false,
                id: 8,
                failed: true,
                test: 3,
                testType: 2
            }, {
                "@УстройстваПользователя": 9651944,
                Доверенное: false,
                Мое: true,
                NewDevice: "0d12c7d2-2fa0-2c2a-3cae-7b62ace9dd63",
                Название: "TSD-KRAS",
                Пользователь: 861523,
                IP: "10.76.190.133",
                ПоследнийВход: "2020-04-14 14:24:10.816342+03",
                ОС: "Windows 7",
                Браузер: "Chrome 80.0.3987",
                Город: "Ярославль",
                ВСети: false,
                Work: true,
                New: false,
                Blocked: null,
                type: 1,
                real_name: "TSD-KRAS",
                archive: false,
                EnterType:'00ba',
                Status: 2,
                model: null,
                is_plugin: true,
                id: 0,
                failed: true,
                testType: 1
            },
            {
                "@УстройстваПользователя": 9912662,
                Доверенное: false,
                Мое: false,
                NewDevice: "93a6a62a-313e-65a3-675c-5478c1f02c16",
                Название: "R78-ZAHMATOV",
                Пользователь: 861523,
                IP: "10.176.134.156",
                ПоследнийВход: "2020-04-14 14:25:18.856370+03",
                ОС: "Windows 10",
                Браузер: "Chrome 80.0.3987",
                Город: "Рыбинск",
                ВСети: false,
                Work: null,
                New: false,
                Blocked: null,
                type: 0,
                real_name: "R78-ZAHMATOV",
                archive: false,
                EnterType: "00ba",
                Status: 2,
                model: null,
                is_plugin: true,
                id: 1,
                failed: true,
                testType: 0
            },
            {
                "@УстройстваПользователя": 9692623,
                Доверенное: false,
                Мое: false,
                NewDevice: "a6047745-879e-c413-7f36-0f1f41661a85",
                Название: "R44-COMP90",
                Пользователь: 861523,
                IP: "10.44.15.37",
                ПоследнийВход: "2020-04-14 14:24:56.522297+03",
                ОС: "Windows 7",
                Браузер: "Chrome 80.0.3987",
                Город: "Кострома",
                ВСети: false,
                Work: false,
                New: false,
                Blocked: null,
                type: 0,
                real_name: "R44-COMP90",
                archive: false,
                EnterType: "00ba",
                Status: 2,
                model: null,
                is_plugin: true,
                id: 2,
                failed: true,
                testType: 1
            },
            {
                "@УстройстваПользователя": 9711945,
                Доверенное: false,
                Мое: false,
                NewDevice: "ee0001e8-2ea4-79ec-2a8c-f846636eb219",
                Название: "R78-DOLMATOV2",
                Пользователь: 861523,
                IP: "10.78.14.56",
                ПоследнийВход: "2020-04-14 14:24:52.911089+03",
                ОС: "Windows 10",
                Браузер: "Chrome 80.0.3987",
                Город: "Санкт-Петербург",
                ВСети: false,
                Work: null,
                New: false,
                Blocked: null,
                type: 0,
                real_name: "R78-DOLMATOV2",
                archive: false,
                EnterType: "00ba",
                Status: 2,
                model: null,
                is_plugin: true,
                id: 3,
                failed: true,
                testType: 1
            },
            {
                "@УстройстваПользователя": 9716185,
                Доверенное: false,
                Мое: false,
                NewDevice: "800e73b9-b271-2235-348d-cbacb79801aa",
                Название: "R72-PROG40",
                Пользователь: 861523,
                IP: "10.176.131.64",
                ПоследнийВход: "2020-04-14 14:24:47.361597+03",
                ОС: "Windows 7",
                Браузер: "Chrome 80.0.3987",
                Город: "Рыбинск",
                ВСети: false,
                Work: null,
                New: false,
                Blocked: null,
                type: 0,
                real_name: "R72-PROG40",
                archive: false,
                EnterType: "00ba",
                Status: 2,
                model: null,
                is_plugin: true,
                id: 4,
                failed: true
            },
            {
                "@УстройстваПользователя": 9741827,
                Доверенное: false,
                Мое: false,
                NewDevice: null,
                Название: "Устройство не определено",
                Пользователь: 861523,
                IP: "10.76.146.187",
                ПоследнийВход: "2020-04-14 14:24:41.753436+03",
                ОС: "Other",
                Браузер: "ZabbixCaller",
                Город: "Ярославль",
                ВСети: false,
                Work: false,
                New: false,
                Blocked: false,
                type: 3,
                real_name: "Устройство не определено",
                archive: false,
                EnterType: "00ba",
                Status: 2,
                model: null,
                is_plugin: false,
                id: 5,
                failed: true
            }, {
                "@УстройстваПользователя": 10005208,
                Доверенное: false,
                Мое: false,
                NewDevice: null,
                Название: "Windows 7",
                Пользователь: 861523,
                IP: "10.176.134.144",
                ПоследнийВход: "2020-04-14 14:24:11.476807+03",
                ОС: "Windows 7",
                Браузер: "Chrome 80.0.3987",
                Город: "Рыбинск",
                ВСети: false,
                Work: null,
                New: false,
                Blocked: true,
                type: 0,
                real_name: "Windows 7",
                archive: false,
                EnterType: "00ba",
                Status: 2,
                model: null,
                is_plugin: false,
                id: 6
            }, {
                "@УстройстваПользователя": 9542638,
                Доверенное: false,
                Мое: false,
                NewDevice: "cff59b34-ac20-d344-ecf6-32bfd645c7d8",
                Название: "R78-PROHOROVA",
                Пользователь: 861523,
                IP: "10.78.14.22",
                ПоследнийВход: "2020-04-14 14:20:03.584340+03",
                ОС: "Windows 7",
                Браузер: "Chrome 80.0.3987",
                Город: "Санкт-Петербург",
                ВСети: false,
                Work: null,
                New: false,
                Blocked: true,
                type: 0,
                real_name: "R78-PROHOROVA",
                archive: false,
                EnterType: "00ba",
                Status: 1,
                model: null,
                is_plugin: true,
                id: 7
            }, {
                "@УстройстваПользователя": 10008659,
                Доверенное: false,
                Мое: false,
                NewDevice: null,
                Название: "Windows 10",
                Пользователь: 861523,
                IP: "10.176.132.163",
                ПоследнийВход: "2020-04-14 14:19:24.757207+03",
                ОС: "Windows 10",
                Браузер: "Chrome 80.0.3987",
                Город: "Рыбинск",
                ВСети: false,
                Work: null,
                New: true,
                Blocked: true,
                type: 0,
                real_name: "Windows 10",
                archive: false,
                EnterType: "00ba",
                Status: 1,
                model: null,
                is_plugin: false,
                id: 8
            }, {
                "@УстройстваПользователя": 9651944,
                Доверенное: false,
                Мое: true,
                NewDevice: "0d12c7d2-2fa0-2c2a-3cae-7b62ace9dd63",
                Название: "TSD-KRAS",
                Пользователь: 861523,
                IP: "10.76.190.133",
                ПоследнийВход: "2020-04-14 14:24:10.816342+03",
                ОС: "Windows 7",
                Браузер: "Chrome 80.0.3987",
                Город: "Ярославль",
                ВСети: false,
                Work: true,
                New: false,
                Blocked: true,
                type: 1,
                real_name: "TSD-KRAS",
                archive: false,
                EnterType:'00ba',
                Status: 2,
                model: null,
                is_plugin: true,
                id: 0
            },
            {
                "@УстройстваПользователя": 9912662,
                Доверенное: false,
                Мое: false,
                NewDevice: "93a6a62a-313e-65a3-675c-5478c1f02c16",
                Название: "R78-ZAHMATOV",
                Пользователь: 861523,
                IP: "10.176.134.156",
                ПоследнийВход: "2020-04-14 14:25:18.856370+03",
                ОС: "Windows 10",
                Браузер: "Chrome 80.0.3987",
                Город: "Рыбинск",
                ВСети: false,
                Work: null,
                New: false,
                Blocked: true,
                type: 0,
                real_name: "R78-ZAHMATOV",
                archive: false,
                EnterType: "00ba",
                Status: 2,
                model: null,
                is_plugin: true,
                id: 1
            },
            {
                "@УстройстваПользователя": 9692623,
                Доверенное: false,
                Мое: false,
                NewDevice: "a6047745-879e-c413-7f36-0f1f41661a85",
                Название: "R44-COMP90",
                Пользователь: 861523,
                IP: "10.44.15.37",
                ПоследнийВход: "2020-04-14 14:24:56.522297+03",
                ОС: "Windows 7",
                Браузер: "Chrome 80.0.3987",
                Город: "Кострома",
                ВСети: false,
                Work: false,
                New: false,
                Blocked: true,
                type: 0,
                real_name: "R44-COMP90",
                archive: false,
                EnterType: "00ba",
                Status: 2,
                model: null,
                is_plugin: true,
                id: 2,
            },
            {
                "@УстройстваПользователя": 9711945,
                Доверенное: false,
                Мое: false,
                NewDevice: "ee0001e8-2ea4-79ec-2a8c-f846636eb219",
                Название: "R78-DOLMATOV2",
                Пользователь: 861523,
                IP: "10.78.14.56",
                ПоследнийВход: "2020-04-14 14:24:52.911089+03",
                ОС: "Windows 10",
                Браузер: "Chrome 80.0.3987",
                Город: "Санкт-Петербург",
                ВСети: false,
                Work: null,
                New: false,
                Blocked: true,
                type: 0,
                real_name: "R78-DOLMATOV2",
                archive: false,
                EnterType: "00ba",
                Status: 2,
                model: null,
                is_plugin: true,
                id: 3
            },
            {
                "@УстройстваПользователя": 9716185,
                Доверенное: false,
                Мое: false,
                NewDevice: "800e73b9-b271-2235-348d-cbacb79801aa",
                Название: "R72-PROG40",
                Пользователь: 861523,
                IP: "10.176.131.64",
                ПоследнийВход: "2020-04-14 14:24:47.361597+03",
                ОС: "Windows 7",
                Браузер: "Chrome 80.0.3987",
                Город: "Рыбинск",
                ВСети: false,
                Work: null,
                New: false,
                Blocked: true,
                type: 0,
                real_name: "R72-PROG40",
                archive: false,
                EnterType: "00ba",
                Status: 2,
                model: null,
                is_plugin: true,
                id: 4
            },
            {
                "@УстройстваПользователя": 9741827,
                Доверенное: false,
                Мое: false,
                NewDevice: null,
                Название: "Устройство не определено",
                Пользователь: 861523,
                IP: "10.76.146.187",
                ПоследнийВход: "2020-04-14 14:24:41.753436+03",
                ОС: "Other",
                Браузер: "ZabbixCaller",
                Город: "Ярославль",
                ВСети: false,
                Work: false,
                New: false,
                Blocked: true,
                type: 3,
                real_name: "Устройство не определено",
                archive: false,
                EnterType: "00ba",
                Status: 2,
                model: null,
                is_plugin: false,
                id: 5
            }, {
                "@УстройстваПользователя": 10005208,
                Доверенное: false,
                Мое: false,
                NewDevice: null,
                Название: "Windows 7",
                Пользователь: 861523,
                IP: "10.176.134.144",
                ПоследнийВход: "2020-04-14 14:24:11.476807+03",
                ОС: "Windows 7",
                Браузер: "Chrome 80.0.3987",
                Город: "Рыбинск",
                ВСети: false,
                Work: null,
                New: false,
                Blocked: true,
                type: 0,
                real_name: "Windows 7",
                archive: false,
                EnterType: "00ba",
                Status: 2,
                model: null,
                is_plugin: false,
                id: 6
            }, {
                "@УстройстваПользователя": 9542638,
                Доверенное: false,
                Мое: false,
                NewDevice: "cff59b34-ac20-d344-ecf6-32bfd645c7d8",
                Название: "R78-PROHOROVA",
                Пользователь: 861523,
                IP: "10.78.14.22",
                ПоследнийВход: "2020-04-14 14:20:03.584340+03",
                ОС: "Windows 7",
                Браузер: "Chrome 80.0.3987",
                Город: "Санкт-Петербург",
                ВСети: false,
                Work: null,
                New: false,
                Blocked: true,
                type: 0,
                real_name: "R78-PROHOROVA",
                archive: false,
                EnterType: "00ba",
                Status: 1,
                model: null,
                is_plugin: true,
                id: 7
            }, {
                "@УстройстваПользователя": 10008659,
                Доверенное: false,
                Мое: false,
                NewDevice: null,
                Название: "Windows 10",
                Пользователь: 861523,
                IP: "10.176.132.163",
                ПоследнийВход: "2020-04-14 14:19:24.757207+03",
                ОС: "Windows 10",
                Браузер: "Chrome 80.0.3987",
                Город: "Рыбинск",
                ВСети: false,
                Work: null,
                New: true,
                Blocked: true,
                type: 0,
                real_name: "Windows 10",
                archive: false,
                EnterType: "00ba",
                Status: 1,
                model: null,
                is_plugin: false,
                id: 8
            }

        ]
    };
}

function getActionsForDevices(): IItemAction[] {
    return [
        {
            id: 0,
            icon: 'icon-OutHotel',
            title: 'Завершить сеанс',
            showType: showType.MENU
        },
        {
            id: 1,
            title: 'Заблокировать',
            showType: showType.MENU,
            icon: 'icon-Lock',
            iconStyle: 'danger'
        }, {
            id: 3,
            title: 'Статус устройства',
            'parent@': true,
            showType: showType.MENU,
            parent : null
        }, {
            id: 4,
            title: 'Рабочий компьютер',
            icon: 'icon-TFComputer',
            showType: showType.MENU,
            parent: 3
        }, {
            id: 5,
            title: 'Домашнее устройство',
            icon: 'icon-Home',
            showType: showType.MENU,
            parent: 3
        }, {
            id: 6,
            title: 'Мобильное устройство',
            icon: 'icon-PhoneCell',
            showType: showType.MENU,
            parent: 3
        }, {
            id: 7,
            title: 'Не определено',
            icon: 'icon-QuestionNew',
            showType: showType.MENU,
            parent: 3
        }
    ];
}

function getActionsForBlockedDevices(): IItemAction[] {
    return [
        {
            id: 0,
            icon: 'icon-Unlock',
            title: 'Разблокировать',
            showType: showType.TOOLBAR
        }
    ];
}

function getActionsForFailedTries(): IItemAction[] {
    return [
        {
            id: 0,
            icon: 'icon-Lock',
            title: 'Заблокировать',
            showType: showType.TOOLBAR,
            iconStyle: 'danger'
        }
    ];
}

export {
    getActionsForDevices,
    getActionsForFailedTries,
    getActionsForBlockedDevices,
    getDevicesTrusted,
    getDevicesBlocked,
    getColumns,
    getDevicesFailed
};
