import 'wml!Controls-demo/DevicesInfo/columnTemplates/DevicesInfoDeviceList';
import 'wml!Controls-demo/DevicesInfo/columnTemplates/DevicesInfoDateList';
import 'wml!Controls-demo/DevicesInfo/columnTemplates/DevicesInfoLocationList';
import 'wml!Controls-demo/DevicesInfo/columnTemplates/DevicesInfoIconsList';
import {showType} from 'Controls/Utils/Toolbar';
import {IItemAction} from 'Controls/_list/interface/IList';

function getColumns() {
    return [
        {
            template: 'wml!Controls-demo/DevicesInfo/columnTemplates/DevicesInfoDeviceList',
            width: '3fr'
        }, {
            template: 'wml!Controls-demo/DevicesInfo/columnTemplates/DevicesInfoDateList',
            width: '75px'
        }, {
            template: 'wml!Controls-demo/DevicesInfo/columnTemplates/DevicesInfoLocationList',
            width: '1fr'
        }, {
            template: 'wml!Controls-demo/DevicesInfo/columnTemplates/DevicesInfoIconsList',
            width: '90px'
        }
    ];
}

function getActionsForDevices(): IItemAction[] {
    return [
        {
            id: 0,
            icon: 'icon-OutHotel',
            title: 'Завершить сеанс',
            showType: showType.MENU
        },
        {
            id: 1,
            title: 'Заблокировать',
            showType: showType.MENU,
            icon: 'icon-Lock',
            iconStyle: 'danger'
        }, {
            id: 2,
            title: 'Статус устройства',
            'parent@': true,
            showType: showType.MENU,
            parent : null
        }, {
            id: 3,
            title: 'Рабочий компьютер',
            icon: 'icon-TFComputer',
            showType: showType.MENU,
            parent: 2
        }, {
            id: 4,
            title: 'Домашнее устройство',
            icon: 'icon-Home',
            showType: showType.MENU,
            parent: 2
        }, {
            id: 5,
            title: 'Мобильное устройство',
            icon: 'icon-PhoneCell',
            showType: showType.MENU,
            parent: 2
        }, {
            id: 6,
            title: 'Не определено',
            icon: 'icon-QuestionNew',
            showType: showType.MENU,
            parent: 2
        }
    ];
}

function getActionsForBlockedDevices(): IItemAction[] {
    return [
        {
            id: 0,
            icon: 'icon-Unlock',
            title: 'Разблокировать',
            showType: showType.TOOLBAR
        }
    ];
}

function getActionsForFailedTries(): IItemAction[] {
    return [
        {
            id: 0,
            icon: 'icon-Lock',
            title: 'Заблокировать',
            showType: showType.TOOLBAR,
            iconStyle: 'danger'
        }
    ];
}

function getActivityDevices() {
        return [
            {
                "@Id": 10011608,
                DeviceId: null,
                UserId: 5894891,
                UserAgent: '',
                IsPlugin: true,
                DeviceType: 1,
                Status: 2,
                DeviceKey: "070ee870-d9a7-4438-77a1-cabc52089fed",
                DeviceName: "R54-KOVALEV",
                RealDeviceName: "R54-KOVALEV",
                Browser: "Chrome 80.0.3987",
                City: "Новосибирск",
                DeviceModel: null,
                IP: "10.54.14.102",
                EnterType: "00ba",
                Cause: null,
                CurrentDevice: true,
                Blocked: null,
                Trusted: false,
                Date: "Wed Apr 22 2020 10:03:07 GMT+0700 (Новосибирск, стандартное время)"
            },
            {
                "@Id": 10002074,
                DeviceId: null,
                UserAgent: '',
                IsPlugin: true,
                DeviceType: 0,
                UserId: 5894891,
                Status: 1,
                DeviceKey: "2798cc2d-2e09-fd60-fe41-0cafbe86a666",
                DeviceName: "R78-MELNIKOVA",
                RealDeviceName: "R78-MELNIKOVA",
                Browser: "Yandex Browser 20.3.2",
                City: "Санкт-Петербург",
                DeviceModel: null,
                IP: "10.78.14.166",
                EnterType: "00ba",
                Cause: null,
                CurrentDevice: false,
                Blocked: null,
                Trusted: false,
                Date: "Tue Apr 21 2020 22:43:41 GMT+0700 (Новосибирск, стандартное время)"
            },
            {
                "@Id": 10009311,
                DeviceId: null,
                UserId: 5894891,
                UserAgent: '',
                IsPlugin: true,
                DeviceType: 1,
                Status: 1,
                DeviceKey: "3d6f3e05-e2a9-43de-b978-a9e4419c256c",
                DeviceName: "Windows 10",
                RealDeviceName: "Windows 10",
                Browser: "Chrome 81.0.4044",
                City: "Рыбинск",
                DeviceModel: null,
                IP: "10.176.129.181",
                EnterType: "00ba",
                Cause: null,
                CurrentDevice: false,
                Blocked: null,
                Trusted: false,
                Date: "Tue Apr 21 2020 21:59:04 GMT+0700 (Новосибирск, стандартное время)"
            },
            {
                "@Id": 9991994,
                DeviceId: null,
                UserId: 5894891,
                UserAgent: '',
                IsPlugin: false,
                DeviceType: 1,
                Status: 1,
                DeviceKey: "e3f24bc5-ccee-e752-828d-de207ea8d010",
                DeviceName: "USD-KRASNOGOROV",
                RealDeviceName: "USD-KRASNOGOROV",
                Browser: "Chrome 80.0.3987",
                City: "Ярославль",
                DeviceModel: null,
                IP: "10.76.175.6",
                EnterType: "00ba",
                Cause: null,
                CurrentDevice: false,
                Blocked: null,
                Trusted: false,
                Date: "Tue Apr 21 2020 20:37:23 GMT+0700 (Новосибирск, стандартное время)"
            },
            {
                "@Id": 9922217,
                DeviceId: null,
                UserAgent: '',
                IsPlugin: false,
                DeviceType: 3,
                UserId: 5894891,
                Status: 1,
                DeviceKey: "5d4358e9-9fc6-05c0-91d4-c8c44055880b",
                DeviceName: "USD-ANDRONOV1",
                RealDeviceName: "USD-ANDRONOV1",
                Browser: "Chrome 80.0.3987",
                City: "Ярославль",
                DeviceModel: null,
                IP: "10.76.174.184",
                EnterType: "00ba",
                Cause: null,
                CurrentDevice: false,
                Blocked: null,
                Trusted: false,
                Date: "Tue Apr 21 2020 18:43:03 GMT+0700 (Новосибирск, стандартное время)"
            },
            {
                "@Id": 9919504,
                DeviceId: null,
                UserAgent: '',
                IsPlugin: true,
                DeviceType: 2,
                UserId: 5894891,
                Status: 1,
                DeviceKey: "72a669a1-ed9c-648c-ccc4-70614bd1d624",
                DeviceName: "R44-LUKASHENKO",
                RealDeviceName: "R44-LUKASHENKO",
                Browser: "Chrome 81.0.4044",
                City: "Кострома",
                DeviceModel: null,
                IP: "10.44.14.60",
                EnterType: "00ba",
                Cause: null,
                CurrentDevice: false,
                Blocked: null,
                Trusted: false,
                Date: "Tue Apr 21 2020 18:02:45 GMT+0700 (Новосибирск, стандартное время)"
            },
            {
                "@Id": 9996779,
                DeviceId: null,
                UserId: 5894891,
                UserAgent: '',
                IsPlugin: true,
                DeviceType: 1,
                Status: 1,
                DeviceKey: "d0f218bf-0074-4984-b842-8c4be4c19129",
                DeviceName: "Windows 10",
                RealDeviceName: "Windows 10",
                Browser: "Chrome 81.0.4044",
                City: "Рыбинск",
                DeviceModel: null,
                IP: "10.176.133.127",
                EnterType: "00ba",
                Cause: null,
                CurrentDevice: false,
                Blocked: null,
                Trusted: false,
                Date: "Wed Apr 15 2020 18:24:38 GMT+0700 (Новосибирск, стандартное время)"
            },
            {
                "@Id": 9968135,
                DeviceId: null,
                UserId: 5894891,
                UserAgent: '',
                IsPlugin: true,
                DeviceType: 1,
                Status: 1,
                DeviceKey: "d7e586b7-2ba5-0f93-c9b2-59878a8b5b9e",
                DeviceName: "R78-GUSEV",
                RealDeviceName: "R78-GUSEV",
                Browser: "Chrome 80.0.3987",
                City: "Рыбинск",
                DeviceModel: null,
                IP: "10.176.128.22",
                EnterType: "00ba",
                Cause: null,
                CurrentDevice: false,
                Blocked: null,
                Trusted: false,
                Date: "Thu Mar 19 2020 16:38:45 GMT+0700 (Новосибирск, стандартное время)"
            },
            {
                "@Id": 9996242,
                DeviceId: null,
                UserId: 5894891,
                UserAgent: '',
                IsPlugin: false,
                DeviceType: 0,
                Status: 1,
                DeviceKey: "e251d209-b65e-3b7f-8860-01940c62bbda",
                DeviceName: "DESKTOP-6B09GDL",
                RealDeviceName: "DESKTOP-6B09GDL",
                Browser: "Chrome 80.0.3987",
                City: "Ярославль",
                DeviceModel: null,
                IP: "10.76.146.37",
                EnterType: "00ba",
                Cause: null,
                CurrentDevice: false,
                Blocked: null,
                Trusted: false,
                Date: "Wed Mar 18 2020 20:12:45 GMT+0700 (Новосибирск, стандартное время)"
            },
            {
                "@Id": 9924338,
                DeviceId: null,
                UserId: 5894891,
                UserAgent: '',
                IsPlugin: true,
                DeviceType: 1,
                Status: 1,
                DeviceKey: "b9a1e8c0-dbe2-2971-38d7-98e74e556ddc",
                DeviceName: "USD-DRUZHINEC1",
                RealDeviceName: "USD-DRUZHINEC1",
                Browser: "Chrome 80.0.3987",
                City: "Ярославль",
                DeviceModel: null,
                IP: "10.76.180.119",
                EnterType: "00ba",
                Cause: null,
                CurrentDevice: false,
                Blocked: null,
                Trusted: false,
                Date: "Mon Mar 16 2020 19:12:52 GMT+0700 (Новосибирск, стандартное время)"
            },
            {
                "@Id": 9987609,
                DeviceId: null,
                UserId: 5894891,
                UserAgent: '',
                IsPlugin: true,
                DeviceType: 1,
                Status: 1,
                DeviceKey: "2a832238-7b85-452c-b53e-5df30c70b005",
                DeviceName: "Mac OS X 10.14.6",
                RealDeviceName: "Mac OS X 10.14.6",
                Browser: "Chrome 78.0.3904",
                City: "Санкт-Петербург",
                DeviceModel: null,
                IP: "10.78.14.210",
                EnterType: "00ba",
                Cause: null,
                CurrentDevice: false,
                Blocked: null,
                Trusted: false,
                Date: "Tue Feb 25 2020 18:12:00 GMT+0700 (Новосибирск, стандартное время)"
            }
        ];
}

function getFailingAuth() {
    return [
        {
            "@Id": 377398,
            DeviceId: 9922217,
            UserId: null,
            UserAgent: '',
            IsPlugin: true,
            DeviceType: 1,
            Status: null,
            DeviceKey: "5d4358e9-9fc6-05c0-91d4-c8c44055880b",
            DeviceName: "USD-ANDRONOV1",
            RealDeviceName: null,
            Browser: null,
            City: "Санкт-Петербург",
            DeviceModel: null,
            IP: "10.76.174.184",
            EnterType: null,
            Cause: "Ввод неправильного пароля",
            CurrentDevice: null,
            Blocked: null,
            Trusted: false,
            Date: "Thu Apr 16 2020 14:36:03 GMT+0700 (Новосибирск, стандартное время)"
        },
        {
            "@Id": 374420,
            DeviceId: null,
            UserId: null,
            UserAgent: '',
            IsPlugin: true,
            DeviceType: 1,
            Status: null,
            DeviceKey: "e89b4c28-5e7e-4cb1-bd68-f035a69ad8f1",
            DeviceName: "Устройство не определено",
            RealDeviceName: null,
            Browser: null,
            City: "Ярославль",
            DeviceModel: null,
            IP: "10.176.134.184",
            EnterType: null,
            Cause: "Ввод неправильного пароля",
            CurrentDevice: null,
            Blocked: null,
            Trusted: null,
            Date: "Tue Mar 31 2020 14:03:19 GMT+0700 (Новосибирск, стандартное время)"
        },
        {
            "@Id": 372834,
            DeviceId: 10004977,
            UserId: null,
            Status: null,
            UserAgent: '',
            IsPlugin: false,
            DeviceType: 1,
            DeviceKey: "f4c6eb37-fabe-1d39-49ac-0b8e28430b70",
            DeviceName: "R78-EGOROV",
            RealDeviceName: null,
            Browser: null,
            City: "Санкт-Петербург",
            DeviceModel: null,
            IP: "10.78.14.194",
            EnterType: null,
            Cause: "Ввод неправильного пароля",
            CurrentDevice: null,
            Blocked: null,
            Trusted: false,
            Date: "Thu Mar 19 2020 19:30:43 GMT+0700 (Новосибирск, стандартное время)"
        },
        {
            "@Id": 372701,
            DeviceId: 9996779,
            UserId: null,
            UserAgent: '',
            IsPlugin: false,
            DeviceType: 3,
            Status: null,
            DeviceKey: "d0f218bf-0074-4984-b842-8c4be4c19129",
            DeviceName: "Windows 10",
            RealDeviceName: null,
            Browser: null,
            City: "Санкт-Петербург",
            DeviceModel: null,
            IP: "10.176.128.197",
            EnterType: null,
            Cause: "Ввод неправильного пароля",
            CurrentDevice: null,
            Blocked: null,
            Trusted: false,
            Date: "Thu Mar 19 2020 13:32:19 GMT+0700 (Новосибирск, стандартное время)"
        },
        {
            "@Id": 369899,
            DeviceId: 9989704,
            UserId: null,
            Status: null,
            UserAgent: '',
            IsPlugin: true,
            DeviceType: 2,
            DeviceKey: "ac1fcad0-a2da-3f45-1903-6c331f79fa98",
            DeviceName: "USD-PROG205",
            RealDeviceName: null,
            Browser: null,
            City: "Санкт-Петербург",
            DeviceModel: null,
            IP: "10.76.174.135",
            EnterType: null,
            Cause: "Ввод неправильного пароля",
            CurrentDevice: null,
            Blocked: null,
            Trusted: false,
            Date: "Wed Mar 04 2020 20:56:01 GMT+0700 (Новосибирск, стандартное время)"
        },
        {
            "@Id:" 361021,
            DeviceId: 9991994,
            UserId: null,
            UserAgent: '',
            IsPlugin: false,
            DeviceType: 1,
            Status: null,
            DeviceKey: "e3f24bc5-ccee-e752-828d-de207ea8d010",
            DeviceName: "USD-KRASNOGOROV",
            RealDeviceName: null,
            Browser: null,
            City: "Санкт-Петербург",
            DeviceModel: null,
            IP: "10.76.175.6",
            EnterType: null,
            Cause: "Ввод неправильного пароля",
            CurrentDevice: null,
            Blocked: null,
            Trusted: false,
            Date: "Tue Jan 28 2020 18:52:54 GMT+0700 (Новосибирск, стандартное время)"
        },
        {
            "@Id": 361020,
            DeviceId: 9991994,
            UserAgent: '',
            IsPlugin: true,
            DeviceType: 1,
            UserId: null,
            Status: null,
            DeviceKey: "e3f24bc5-ccee-e752-828d-de207ea8d010",
            DeviceName: "USD-KRASNOGOROV",
            RealDeviceName: null,
            Browser: null,
            City: "Рыбинск",
            DeviceModel: null,
            IP: "10.76.175.6",
            EnterType: null,
            Cause: "Ввод неправильного пароля",
            CurrentDevice: null,
            Blocked: null,
            Trusted: false,
            Date: "Tue Jan 28 2020 18:52:39 GMT+0700 (Новосибирск, стандартное время)"
        },
        {
            "@Id": 360713,
            DeviceId: 9926523,
            UserAgent: '',
            IsPlugin: false,
            DeviceType: 2,
            UserId: null,
            Status: null,
            DeviceKey: "eb77adc6-91c2-f4c4-bb4a-8e333d4cfd26",
            DeviceName: "USD-ELIFANTEV",
            RealDeviceName: null,
            Browser: null,
            City: "Рыбинск",
            DeviceModel: null,
            IP: "10.76.174.218",
            EnterType: null,
            Cause: "Ввод неправильного пароля",
            CurrentDevice: null,
            Blocked: null,
            Trusted: false,
            Date: "Mon Jan 27 2020 23:01:09 GMT+0700 (Новосибирск, стандартное время)"
        },
        {
            "@Id": 359646,
            DeviceId: null,
            UserAgent: '',
            IsPlugin: true,
            DeviceType: 1,
            UserId: null,
            Status: null,
            DeviceKey: "0a2d4b6f-9f8b-03d1-45a9-35ee8c8340c3",
            DeviceName: "Устройство не определено",
            RealDeviceName: null,
            Browser: null,
            City: "Рыбинск",
            DeviceModel: null,
            IP: "10.16.14.46",
            EnterType: null,
            Cause: "Ввод неправильного пароля",
            CurrentDevice: null,
            Blocked: null,
            Trusted: null,
            Date: "Thu Jan 23 2020 14:34:56 GMT+0700 (Новосибирск, стандартное время)"
        },
        {
            "@Id": 359645,
            DeviceId: null,
            UserAgent: '',
            IsPlugin: true,
            DeviceType: 1,
            UserId: null,
            Status: null,
            DeviceKey: "0a2d4b6f-9f8b-03d1-45a9-35ee8c8340c3",
            DeviceName: "Устройство не определено",
            RealDeviceName: null,
            Browser: null,
            City: "Санкт-Петербург",
            DeviceModel: null,
            IP: "10.16.14.46",
            EnterType: null,
            Cause: "Ввод неправильного пароля",
            CurrentDevice: null,
            Blocked: null,
            Trusted: null,
            Date: "Thu Jan 23 2020 14:34:47 GMT+0700 (Новосибирск, стандартное время)"
        },
        {
            "@Id": 341122,
            DeviceId: 9949202,
            UserId: null,
            Status: null,
            UserAgent: '',
            IsPlugin: true,
            DeviceType: 1,
            DeviceKey: "c790a921-9723-4f7d-8f18-a7e9221e3928",
            DeviceName: "iPad",
            RealDeviceName: null,
            Browser: null,
            City: "Новосибирск",
            DeviceModel: null,
            IP: "10.44.8.133",
            EnterType: null,
            Cause: "Ввод неправильного пароля",
            CurrentDevice: null,
            Blocked: null,
            Trusted: false,
            Date: "Fri Oct 25 2019 21:52:59 GMT+0700 (Новосибирск, стандартное время)"
        },
        {
            "@Id": 339055,
            DeviceId: 9919504,
            UserId: null,
            Status: null,
            UserAgent: '',
            IsPlugin: true,
            DeviceType: 1,
            DeviceKey: "72a669a1-ed9c-648c-ccc4-70614bd1d624",
            DeviceName: "R44-LUKASHENKO",
            RealDeviceName: null,
            Browser: null,
            City: "Ярославль",
            DeviceModel: null,
            IP: "10.44.14.60",
            EnterType: null,
            Cause: "Ввод неправильного пароля",
            CurrentDevice: null,
            Blocked: null,
            Trusted: false,
            Date: "Mon Oct 21 2019 13:51:00 GMT+0700 (Новосибирск, стандартное время)"
        },
        {
            "@Id": 332338,
            DeviceId: 9921773,
            UserId: null,
            Status: null,
            DeviceKey: "0915033e-ba8d-7d14-8a3d-b9e15915ebf8",
            DeviceName: "R78-EGOROV",
            RealDeviceName: null,
            Browser: null,
            UserAgent: '',
            IsPlugin: false,
            DeviceType: 3,
            City: "Санкт-Петербург",
            DeviceModel: null,
            IP: "10.78.14.194",
            EnterType: null,
            Cause: "Ввод неправильного пароля",
            CurrentDevice: null,
            Blocked: null,
            Trusted: false,
            Date: "Mon Sep 23 2019 18:28:16 GMT+0700 (Новосибирск, стандартное время)"
        },
        {
            "@Id": 330170,
            DeviceId: 9923316,
            UserId: null,
            UserAgent: '',
            IsPlugin: true,
            DeviceType: 0,
            Status: null,
            DeviceKey: "15077af4-a5fe-83c6-3848-527127ac091d",
            DeviceName: "R78-GUSEV",
            RealDeviceName: null,
            Browser: null,
            City: "Рыбинск",
            DeviceModel: null,
            IP: "10.78.14.140",
            EnterType: null,
            Cause: "Ввод неправильного пароля",
            CurrentDevice: null,
            Blocked: null,
            Trusted: false,
            Date: "Wed Sep 11 2019 15:03:58 GMT+0700 (Новосибирск, стандартное время)"
        },
        {
            "@Id": 329921,
            DeviceId: 9923316,
            UserId: null,
            UserAgent: '',
            IsPlugin: true,
            DeviceType: 0,
            Status: null,
            DeviceKey: "15077af4-a5fe-83c6-3848-527127ac091d",
            DeviceName: "R78-GUSEV",
            RealDeviceName: null,
            Browser: null,
            City: "",
            DeviceModel: null,
            IP: "10.78.14.140",
            EnterType: null,
            Cause: "Ввод неправильного пароля",
            CurrentDevice: null,
            Blocked: null,
            Trusted: false,
            Date: "Tue Sep 10 2019 18:52:33 GMT+0700 (Новосибирск, стандартное время)"
        },
        {
            "@Id": 329920,
            DeviceId: 9923316,
            UserId: null,
            UserAgent: '',
            IsPlugin: false,
            DeviceType: 1,
            Status: null,
            DeviceKey: "15077af4-a5fe-83c6-3848-527127ac091d",
            DeviceName: "R78-GUSEV",
            RealDeviceName: null,
            Browser: null,
            City: "Санкт-Петербург",
            DeviceModel: null,
            IP: "10.78.14.140",
            EnterType: null,
            Cause: "Ввод неправильного пароля",
            CurrentDevice: null,
            Blocked: null,
            Trusted: false,
            Date: "Tue Sep 10 2019 18:52:29 GMT+0700 (Новосибирск, стандартное время)"
        },
        {
            "@Id": 326792,
            DeviceId: 9921773,
            UserId: null,
            UserAgent: '',
            IsPlugin: true,
            DeviceType: 1,
            Status: null,
            DeviceKey: "0915033e-ba8d-7d14-8a3d-b9e15915ebf8",
            DeviceName: "R78-EGOROV",
            RealDeviceName: null,
            Browser: null,
            City: "Санкт-Петербург",
            DeviceModel: null,
            IP: "10.78.14.194",
            EnterType: null,
            Cause: "Ввод неправильного пароля",
            CurrentDevice: null,
            Blocked: null,
            Trusted: false,
            Date: "Thu Sep 05 2019 16:54:25 GMT+0700 (Новосибирск, стандартное время)"
        },
        {
            "@Id": 323124,
            DeviceId: 9919504,
            UserId: null,
            UserAgent: '',
            IsPlugin: true,
            DeviceType: 1,
            Status: null,
            DeviceKey: "72a669a1-ed9c-648c-ccc4-70614bd1d624",
            DeviceName: "R44-LUKASHENKO",
            RealDeviceName: null,
            Browser: null,
            City: "Санкт-Петербург",
            DeviceModel: null,
            IP: "10.44.14.60",
            EnterType: null,
            Cause: "Ввод неправильного пароля",
            CurrentDevice: null,
            Blocked: null,
            Trusted: false,
            Date: "Tue Sep 03 2019 16:02:17 GMT+0700 (Новосибирск, стандартное время)"
        }
    ];
}

function getLockedDevices() {
    return [
        {
            "@Id": 9987779,
            DeviceId: null,
            UserId: 58964891,
            Status: 0,
            DeviceKey: "2a832238-7b85-452c-b53e-5df30c70b005",
            DeviceName: "Mac OS X 10.14.6",
            RealDeviceName: "Mac OS X 10.14.6",
            Browser: "Chrome 78.0.3904",
            City: "Санкт-Петербург",
            DeviceType: 0,
            IsPlugin: true,
            DeviceModel: null,
            IP: "10.78.14.210",
            EnterType: "00ba",
            Cause: null,
            CurrentDevice: false,
            Blocked: true,
            Trusted: false,
            Date: "Tue Feb 25 2020 18:12:00 GMT+0700 (Новосибирск, стандартное время)"
        }
    ];
}

export {
    getActionsForDevices,
    getActionsForFailedTries,
    getActionsForBlockedDevices,
    getColumns,
    getActivityDevices,
    getFailingAuth,
    getLockedDevices
};
